/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Atttacker;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author raje
 */
public class Cluster1 extends javax.swing.JFrame {

    /**
     * Creates new form Cluster1
     */
    public Cluster1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cluster-1");
        setFocusable(false);
        setMinimumSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Node 2");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(100, 40, 70, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Node 3");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(100, 90, 70, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Node 5");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(100, 140, 70, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Node 6");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(100, 190, 70, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Node 7");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(100, 240, 70, 30);

        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextfield1(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(160, 40, 150, 30);

        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2(evt);
            }
        });
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(160, 90, 150, 30);

        jTextField3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField3(evt);
            }
        });
        jPanel1.add(jTextField3);
        jTextField3.setBounds(160, 140, 150, 30);

        jTextField4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField4(evt);
            }
        });
        jPanel1.add(jTextField4);
        jTextField4.setBounds(160, 190, 150, 30);

        jTextField5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField5(evt);
            }
        });
        jPanel1.add(jTextField5);
        jTextField5.setBounds(160, 240, 150, 30);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Assign IP Address");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(80, 310, 160, 30);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(270, 310, 110, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Atttacker/globe-background-blue.jpg"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(-770, 0, 1760, 400);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(40, 30, 410, 370);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Atttacker/Textures_wallpapers_379.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(-30, -20, 2380, 470);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-498)/2, (screenSize.height-479)/2, 498, 479);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextfield1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextfield1
       jTextField1.setText("127.0.0.1");
    }//GEN-LAST:event_jTextfield1

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
       // jTextField1.setText("127.0.0.1");
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2
      jTextField2.setText("127.0.0.1");
    }//GEN-LAST:event_jTextField2

    private void jTextField3(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField3
       jTextField3.setText("127.0.0.1");
    }//GEN-LAST:event_jTextField3

    private void jTextField4(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField4
       jTextField4.setText("127.0.0.1");
    }//GEN-LAST:event_jTextField4

    private void jTextField5(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField5
         jTextField5.setText("127.0.0.1");
    }//GEN-LAST:event_jTextField5

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   
        if(jTextField1.getText().equals("")||jTextField2.getText().equals(null)||jTextField3.getText().equals("")||jTextField4.getText().equals("")||jTextField5.getText().equals(""))
       {
           JOptionPane.showMessageDialog(null,"Enter IP Address");
       }
          else{
            try{
                
           //  String getUser = jComboBox1.getSelectedItem().toString();
            Connection con =Spoofing.getConnection();
            Statement st = con.createStatement();

          ///  int i = st.executeUpdate("update node set ip_address='"+jTextField1.getText()+"' where node_name='Node 2' ");
            //int i=st.executeUpdate("update node set (ip_address,status) values('"+jTextField1.getText()+"','Updated') where node_name='Node 3' ");
int i=st.executeUpdate("update node set ip_address='"+jTextField1.getText()+"',status='Default' where node_name='Node 2'");
int a=st.executeUpdate("update node set ip_address='"+jTextField2.getText()+"',status='Default' where node_name='Node 3'");
int b=st.executeUpdate("update node set ip_address='"+jTextField3.getText()+"',status='Default' where node_name='Node 5'");
int c=st.executeUpdate("update node set ip_address='"+jTextField4.getText()+"',status='Default' where node_name='Node 6'");
int d=st.executeUpdate("update node set ip_address='"+jTextField4.getText()+"',status='Default' where node_name='Node 7'");

  }catch(Exception e)
            {
                 e.printStackTrace();
                System.exit(1);
            }
            
            
           JOptionPane.showMessageDialog(null," IP Address Assigned");
       }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       jTextField1.setText(null);
          jTextField2.setText(null);
             jTextField3.setText(null);
                jTextField4.setText(null);
                   jTextField5.setText(null);
                     
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cluster1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cluster1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cluster1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cluster1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cluster1().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
