/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Atttacker;

import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author raje
 */
public class Cluster3 extends javax.swing.JFrame {

    /**
     * Creates new form Cluster3
     */
    public Cluster3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cluster-3");
        setMinimumSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Node 16");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 40, 60, 20);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Node 17");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 90, 60, 20);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Node 19");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 140, 60, 20);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Node 20");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 200, 60, 20);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Assign IP Address");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(30, 270, 160, 30);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(210, 270, 110, 30);

        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(130, 40, 190, 30);

        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(130, 90, 190, 30);

        jTextField3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField3(evt);
            }
        });
        jPanel1.add(jTextField3);
        jTextField3.setBounds(130, 140, 190, 30);

        jTextField4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField4(evt);
            }
        });
        jPanel1.add(jTextField4);
        jTextField4.setBounds(130, 190, 190, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Atttacker/globe-background-blue.jpg"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(-770, -20, 1200, 380);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(40, 40, 380, 350);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Atttacker/Textures_wallpapers_379.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(-20, -10, 500, 470);

        setSize(new java.awt.Dimension(490, 490));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 jTextField1.setText(null);
          jTextField2.setText(null);
             jTextField3.setText(null);
                jTextField4.setText(null);       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1
      jTextField1.setText("127.0.0.1");
            
    }//GEN-LAST:event_jTextField1

    private void jTextField2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2
          jTextField2.setText("127.0.0.1");
    }//GEN-LAST:event_jTextField2

    private void jTextField3(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField3
          jTextField3.setText("127.0.0.1");
    }//GEN-LAST:event_jTextField3

    private void jTextField4(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField4
           jTextField4.setText("127.0.0.1");
    }//GEN-LAST:event_jTextField4

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         if(jTextField1.getText().equals("")||jTextField2.getText().equals(null)||jTextField3.getText().equals("")||jTextField4.getText().equals(""))
       {
           JOptionPane.showMessageDialog(null,"Enter IP Address");
       }
       else{
             
             
                 
         try{
                
           //  String getUser = jComboBox1.getSelectedItem().toString();
            Connection con =Spoofing.getConnection();
            Statement st = con.createStatement();

          ///  int i = st.executeUpdate("update node set ip_address='"+jTextField1.getText()+"' where node_name='Node 2' ");
            //int i=st.executeUpdate("update node set (ip_address,status) values('"+jTextField1.getText()+"','Updated') where node_name='Node 3' ");


int a=st.executeUpdate("update node set ip_address='"+jTextField1.getText()+"',status='Default' where node_name='Node 16'");
int b=st.executeUpdate("update node set ip_address='"+jTextField2.getText()+"',status='Default' where node_name='Node 17'");
int c=st.executeUpdate("update node set ip_address='"+jTextField3.getText()+"',status='Default' where node_name='Node 19'");
int d=st.executeUpdate("update node set ip_address='"+jTextField4.getText()+"',status='Default' where node_name='Node 20'");
//int i=st.executeUpdate("update node set ip_address='"+jTextField7.getText()+"',status='Updated' where node_name='Node 9'");
  }catch(Exception e)
            {
                 e.printStackTrace();
                System.exit(1);
            }
             
             
             
             
             
             
             
             
             
           JOptionPane.showMessageDialog(null," IP Address Assigned");
           new Attacker1().setVisible(true);
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cluster3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cluster3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cluster3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cluster3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cluster3().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
