/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Atttacker;

import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author raje
 */
public class Cluster2 extends javax.swing.JFrame {

    /**
     * Creates new form Cluster2
     */
    public Cluster2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cluster-2");
        setMinimumSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Node 9");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(80, 50, 70, 20);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Node 10");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(80, 100, 70, 20);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Node 12");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(80, 150, 70, 20);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Node 13");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(80, 200, 70, 20);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("Node 14");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(80, 250, 70, 20);

        jTextField7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField7(evt);
            }
        });
        jPanel1.add(jTextField7);
        jTextField7.setBounds(170, 40, 190, 30);

        jTextField8.setName(""); // NOI18N
        jTextField8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField8(evt);
            }
        });
        jPanel1.add(jTextField8);
        jTextField8.setBounds(170, 90, 190, 30);

        jTextField9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField9(evt);
            }
        });
        jPanel1.add(jTextField9);
        jTextField9.setBounds(170, 140, 190, 30);

        jTextField10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField10(evt);
            }
        });
        jPanel1.add(jTextField10);
        jTextField10.setBounds(170, 200, 190, 30);

        jTextField11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField11(evt);
            }
        });
        jPanel1.add(jTextField11);
        jTextField11.setBounds(170, 250, 190, 30);

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setText("Assign IP Address");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(50, 320, 170, 30);

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setText("Reset");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(250, 320, 140, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Atttacker/globe-background-blue.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(-760, 0, 1860, 370);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(50, 40, 440, 370);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Atttacker/Textures_wallpapers_379.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, -20, 570, 500);

        setSize(new java.awt.Dimension(546, 502));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField7(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField7
       jTextField7.setText("127.0.0.1");
    }//GEN-LAST:event_jTextField7

    private void jTextField8(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField8
       jTextField8.setText("127.0.0.1");
               
    }//GEN-LAST:event_jTextField8

    private void jTextField9(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField9
         jTextField9.setText("127.0.0.1");
    }//GEN-LAST:event_jTextField9

    private void jTextField10(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField10
        jTextField10.setText("127.0.0.1");
    }//GEN-LAST:event_jTextField10

    private void jTextField11(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField11
         jTextField11.setText("127.0.0.1");
    }//GEN-LAST:event_jTextField11

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        if(jTextField7.getText().equals("")||jTextField8.getText().equals(null)||jTextField9.getText().equals("")||jTextField10.getText().equals("")||jTextField11.getText().equals(""))
       {
           JOptionPane.showMessageDialog(null,"Enter IP Address");
       }
        
        
        
        
        
    
        
       else{
            
            
         try{
                
           //  String getUser = jComboBox1.getSelectedItem().toString();
            Connection con =Spoofing.getConnection();
            Statement st = con.createStatement();

          ///  int i = st.executeUpdate("update node set ip_address='"+jTextField1.getText()+"' where node_name='Node 2' ");
            //int i=st.executeUpdate("update node set (ip_address,status) values('"+jTextField1.getText()+"','Updated') where node_name='Node 3' ");


int a=st.executeUpdate("update node set ip_address='"+jTextField8.getText()+"',status='Default' where node_name='Node 10'");
int b=st.executeUpdate("update node set ip_address='"+jTextField9.getText()+"',status='Default' where node_name='Node 12'");
int c=st.executeUpdate("update node set ip_address='"+jTextField10.getText()+"',status='Default' where node_name='Node 13'");
int d=st.executeUpdate("update node set ip_address='"+jTextField11.getText()+"',status='Default' where node_name='Node 14'");
int i=st.executeUpdate("update node set ip_address='"+jTextField7.getText()+"',status='Default' where node_name='Node 9'");
  }catch(Exception e)
            {
                 e.printStackTrace();
                System.exit(1);
            }
            
            
            
            
            
            
            
            
            
            
            
           JOptionPane.showMessageDialog(null," IP Address Assigned");
       }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         jTextField7.setText(null);
          jTextField8.setText(null);
             jTextField9.setText(null);
                jTextField10.setText(null);
                   jTextField11.setText(null);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cluster2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cluster2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cluster2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cluster2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cluster2().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
