/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Atttacker;

/**
 *
 * @author m
 */
public class Router1 extends javax.swing.JFrame {

    /**
     * Creates new form Router1
     */
    public Router1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel70 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel71 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(null);

        jToolBar1.setRollover(true);
        getContentPane().add(jToolBar1);
        jToolBar1.setBounds(0, 0, 686, 40);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Source ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 230, 70, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Atttacker/circle_green.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 190, 60, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Atttacker/circle_green.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 110, 48, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Atttacker/circle_green.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(150, 200, 50, 50);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Atttacker/circle_green.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 270, 50, 60);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Atttacker/circle_green.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(230, 110, 50, 50);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Atttacker/circle_green.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(230, 270, 60, 50);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Atttacker/circle_green.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(300, 190, 50, 60);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Atttacker/1382027991_gtk-go-back-rtl.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(370, 210, 32, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Atttacker/circle_green.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(420, 200, 50, 50);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Atttacker/circle_green.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(490, 120, 50, 50);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Atttacker/circle_green.png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(570, 200, 50, 50);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Atttacker/circle_green.png"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(500, 270, 50, 60);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Atttacker/circle_green.png"))); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(650, 120, 50, 50);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Atttacker/circle_green.png"))); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(720, 200, 48, 50);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Atttacker/circle_green.png"))); // NOI18N
        getContentPane().add(jLabel16);
        jLabel16.setBounds(650, 280, 50, 50);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Atttacker/11.PNG"))); // NOI18N
        getContentPane().add(jLabel17);
        jLabel17.setBounds(580, 340, 32, 50);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Atttacker/circle_green.png"))); // NOI18N
        getContentPane().add(jLabel18);
        jLabel18.setBounds(490, 410, 60, 50);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Atttacker/circle_green.png"))); // NOI18N
        getContentPane().add(jLabel19);
        jLabel19.setBounds(410, 490, 50, 48);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Atttacker/circle_green.png"))); // NOI18N
        getContentPane().add(jLabel20);
        jLabel20.setBounds(570, 490, 60, 50);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Atttacker/circle_green.png"))); // NOI18N
        getContentPane().add(jLabel21);
        jLabel21.setBounds(490, 580, 60, 48);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Atttacker/circle_green.png"))); // NOI18N
        getContentPane().add(jLabel22);
        jLabel22.setBounds(650, 400, 50, 50);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Atttacker/circle_green.png"))); // NOI18N
        getContentPane().add(jLabel23);
        jLabel23.setBounds(730, 490, 48, 50);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Atttacker/circle_green.png"))); // NOI18N
        getContentPane().add(jLabel24);
        jLabel24.setBounds(650, 560, 50, 50);

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel25.setText("Node 2");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(80, 160, 50, 20);

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel26.setText("CH-1");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(150, 250, 60, 20);

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel27.setText("Node 3");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(80, 330, 50, 20);

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel28.setText("Node 5");
        getContentPane().add(jLabel28);
        jLabel28.setBounds(230, 160, 50, 20);

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel29.setText("Node 6");
        getContentPane().add(jLabel29);
        jLabel29.setBounds(300, 240, 50, 20);

        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel30.setText("Node 7");
        getContentPane().add(jLabel30);
        jLabel30.setBounds(230, 330, 50, 20);

        jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel31.setText("Node 8");
        getContentPane().add(jLabel31);
        jLabel31.setBounds(420, 250, 50, 20);

        jLabel32.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel32.setText("Node 9");
        getContentPane().add(jLabel32);
        jLabel32.setBounds(500, 170, 50, 20);

        jLabel33.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel33.setText("Node 10");
        getContentPane().add(jLabel33);
        jLabel33.setBounds(490, 340, 60, 20);

        jLabel34.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel34.setText("CH-2");
        getContentPane().add(jLabel34);
        jLabel34.setBounds(580, 260, 40, 20);

        jLabel35.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel35.setText("Node 12");
        getContentPane().add(jLabel35);
        jLabel35.setBounds(640, 170, 60, 20);

        jLabel36.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel36.setText("Node 13");
        getContentPane().add(jLabel36);
        jLabel36.setBounds(650, 330, 60, 20);

        jLabel37.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel37.setText("Node 14");
        getContentPane().add(jLabel37);
        jLabel37.setBounds(730, 250, 60, 20);

        jLabel38.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel38.setText("Node 15");
        getContentPane().add(jLabel38);
        jLabel38.setBounds(420, 540, 60, 20);

        jLabel39.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel39.setText("Node 16");
        getContentPane().add(jLabel39);
        jLabel39.setBounds(490, 460, 60, 20);

        jLabel40.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel40.setText("Node 17");
        getContentPane().add(jLabel40);
        jLabel40.setBounds(490, 630, 60, 20);

        jLabel41.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel41.setText("CH-3");
        getContentPane().add(jLabel41);
        jLabel41.setBounds(570, 540, 40, 20);

        jLabel42.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel42.setText("Node 19");
        getContentPane().add(jLabel42);
        jLabel42.setBounds(650, 450, 60, 20);

        jLabel43.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel43.setText("Node 20");
        getContentPane().add(jLabel43);
        jLabel43.setBounds(650, 610, 60, 20);

        jLabel44.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel44.setText("Destination");
        getContentPane().add(jLabel44);
        jLabel44.setBounds(730, 540, 80, 20);

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Atttacker/north_east_arrow_u2197_icon_48x48.png"))); // NOI18N
        getContentPane().add(jLabel45);
        jLabel45.setBounds(30, 160, 48, 30);

        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Atttacker/north_east_arrow_u2197_icon_48x48.png"))); // NOI18N
        getContentPane().add(jLabel46);
        jLabel46.setBounds(180, 170, 48, 40);

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Atttacker/south_east_arrow_u2198_icon_48x48.png"))); // NOI18N
        getContentPane().add(jLabel47);
        jLabel47.setBounds(30, 260, 48, 40);

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Atttacker/south_east_arrow_u2198_icon_48x48.png"))); // NOI18N
        getContentPane().add(jLabel48);
        jLabel48.setBounds(120, 160, 48, 40);

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Atttacker/south_east_arrow_u2198_icon_48x48.png"))); // NOI18N
        getContentPane().add(jLabel49);
        jLabel49.setBounds(180, 250, 48, 40);

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Atttacker/north_east_arrow_u2197_icon_48x48.png"))); // NOI18N
        getContentPane().add(jLabel50);
        jLabel50.setBounds(110, 260, 48, 30);

        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Atttacker/south_east_arrow_u2198_icon_48x48.png"))); // NOI18N
        getContentPane().add(jLabel51);
        jLabel51.setBounds(270, 160, 48, 40);

        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Atttacker/north_east_arrow_u2197_icon_48x48.png"))); // NOI18N
        getContentPane().add(jLabel52);
        jLabel52.setBounds(270, 250, 48, 40);

        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Atttacker/north_east_arrow_u2197_icon_48x48.png"))); // NOI18N
        getContentPane().add(jLabel53);
        jLabel53.setBounds(450, 160, 48, 40);

        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Atttacker/south_east_arrow_u2198_icon_48x48.png"))); // NOI18N
        getContentPane().add(jLabel54);
        jLabel54.setBounds(540, 160, 48, 40);

        jLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Atttacker/north_east_arrow_u2197_icon_48x48.png"))); // NOI18N
        getContentPane().add(jLabel55);
        jLabel55.setBounds(530, 250, 48, 40);

        jLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Atttacker/south_east_arrow_u2198_icon_48x48.png"))); // NOI18N
        getContentPane().add(jLabel56);
        jLabel56.setBounds(450, 250, 48, 30);

        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Atttacker/south_east_arrow_u2198_icon_48x48.png"))); // NOI18N
        getContentPane().add(jLabel57);
        jLabel57.setBounds(690, 170, 48, 30);

        jLabel58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Atttacker/north_east_arrow_u2197_icon_48x48.png"))); // NOI18N
        getContentPane().add(jLabel58);
        jLabel58.setBounds(590, 170, 48, 30);

        jLabel59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Atttacker/north_east_arrow_u2197_icon_48x48.png"))); // NOI18N
        getContentPane().add(jLabel59);
        jLabel59.setBounds(690, 260, 48, 30);

        jLabel60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Atttacker/south_east_arrow_u2198_icon_48x48.png"))); // NOI18N
        getContentPane().add(jLabel60);
        jLabel60.setBounds(610, 260, 48, 30);

        jLabel61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Atttacker/north_east_arrow_u2197_icon_48x48.png"))); // NOI18N
        getContentPane().add(jLabel61);
        jLabel61.setBounds(440, 450, 48, 30);

        jLabel62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Atttacker/south_east_arrow_u2198_icon_48x48.png"))); // NOI18N
        getContentPane().add(jLabel62);
        jLabel62.setBounds(540, 450, 48, 30);

        jLabel63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Atttacker/south_east_arrow_u2198_icon_48x48.png"))); // NOI18N
        getContentPane().add(jLabel63);
        jLabel63.setBounds(450, 560, 48, 30);

        jLabel64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Atttacker/north_east_arrow_u2197_icon_48x48.png"))); // NOI18N
        getContentPane().add(jLabel64);
        jLabel64.setBounds(530, 550, 50, 40);

        jLabel65.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Atttacker/north_east_arrow_u2197_icon_48x48.png"))); // NOI18N
        getContentPane().add(jLabel65);
        jLabel65.setBounds(610, 460, 48, 40);

        jLabel66.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Atttacker/south_east_arrow_u2198_icon_48x48.png"))); // NOI18N
        getContentPane().add(jLabel66);
        jLabel66.setBounds(700, 460, 48, 30);

        jLabel67.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Atttacker/south_east_arrow_u2198_icon_48x48.png"))); // NOI18N
        getContentPane().add(jLabel67);
        jLabel67.setBounds(610, 540, 48, 40);

        jLabel68.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Atttacker/north_east_arrow_u2197_icon_48x48.png"))); // NOI18N
        getContentPane().add(jLabel68);
        jLabel68.setBounds(690, 550, 48, 30);

        jLabel69.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel69.setText("Cluster 1");
        getContentPane().add(jLabel69);
        jLabel69.setBounds(230, 80, 110, 20);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("Cluster-1 Status ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 80, 190, 30);

        jLabel70.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel70.setText("Cluster 2");
        getContentPane().add(jLabel70);
        jLabel70.setBounds(550, 90, 120, 20);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("Cluster-2 Status");
        getContentPane().add(jButton2);
        jButton2.setBounds(670, 90, 210, 30);

        jLabel71.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel71.setText("Cluster 3");
        getContentPane().add(jLabel71);
        jLabel71.setBounds(410, 380, 120, 20);

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setText("Cluster-3 Status");
        getContentPane().add(jButton3);
        jButton3.setBounds(290, 320, 170, 30);

        jMenu1.setText("File");

        jMenuItem1.setText("No of Attacker Hits");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("View Spoofing Attackers");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("View Node IP Address");
        jMenu1.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Exit");
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Assign IP Address");

        jMenuItem5.setText("Cluster 1");
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Cluster 2");
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Cluster 3");
        jMenu2.add(jMenuItem7);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Router1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Router1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Router1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Router1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Router1().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
