/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Atttacker;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.ObjectOutputStream;
import java.io.OutputStream;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author raje
 */
public class Service extends javax.swing.JFrame {
 
    InetAddress ip;
    String name, size, packets;

    ObjectOutputStream oos,oos1,oos2;
        OutputStream os,os1,os2;
          ArrayList<String> array = new ArrayList<String>();
    /**
     * Creates new form Service_Provider
     */
    public Service() {
        initComponents();
        jTextField1.setVisible(false);
        jTextArea1.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Service_Provider");
        setMinimumSize(new java.awt.Dimension(500, 600));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 102, 102));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Detection And Localization of Multiple Spoofing Attackers Using Wireless Sensor Networks");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 0, 950, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 950, 30);

        jPanel2.setLayout(null);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(-2, -1, 410, 320);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(250, 10, 20, 200);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 50, 410, 320);

        jPanel3.setLayout(null);
        jPanel3.add(jLabel3);
        jLabel3.setBounds(48, 58, 0, 0);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Atttacker/ip-spoofing.86t.cyrevfz3l9.jpeg"))); // NOI18N
        jPanel3.add(jLabel4);
        jLabel4.setBounds(0, -10, 530, 330);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(430, 50, 530, 320);

        jPanel4.setLayout(null);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Browse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);
        jButton1.setBounds(30, 20, 110, 30);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);
        jButton2.setBounds(170, 20, 100, 30);

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3);
        jButton3.setBounds(290, 20, 100, 30);
        jPanel4.add(jTextField1);
        jTextField1.setBounds(420, 20, 240, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Atttacker/crystal clear (8).jpg"))); // NOI18N
        jPanel4.add(jLabel5);
        jLabel5.setBounds(0, -6, 2690, 80);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(10, 400, 410, 70);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Atttacker/Textures_wallpapers_379.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-30, -26, 2040, 640);

        setSize(new java.awt.Dimension(1002, 530));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
          try {
            JFileChooser fc = new JFileChooser();
            fc.showOpenDialog(fc);
            jTextField1.setText(fc.getSelectedFile().toString());
            File ff = new File(jTextField1.getText().toString());
            Scanner sc = new Scanner(ff);
            while (sc.hasNext()) {
                sc.useDelimiter("");
                jTextArea1.append("" + sc.next());
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Service.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

  try {           
            InetAddress addr = InetAddress.getLocalHost();
                                       String ad = addr.getHostAddress();
                                       System.out.println("IP IS :" + addr.getHostAddress());
                                       String getI = JOptionPane.showInputDialog("Enter your IP address");
                                       System.out.println("GET II:" + getI);
                                       if (ad.trim().equals(getI.trim())) {
                                           JOptionPane.showMessageDialog(null, "File Uploaded Successfully");
                                           JOptionPane.showConfirmDialog(null, "Do You want To connect");
                                          
                                    String message = "IP Spoofer Found in Cluster1 Do You Want To Connect??";
                                   String title = "Really Want to Continue?";
                                   // display the JOptionPane showConfirmDialog
                                   int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
                                    if (reply == JOptionPane.YES_OPTION) {
                                           Router tt  = new Router(jTextArea1.getText(),jTextArea2.getText());
               tt.setVisible(true);
                 tt.t1.start();
                                       
                                       } 
                                               
                                    
                                    
                                    
                                    
                                    
                                    
                                    
                                    
                                    
                                    
                                    else{
                                           
                                        JOptionPane.showMessageDialog(null, "IP Error!");
                                       }
                                       }
        } catch (UnknownHostException ex) {
            Logger.getLogger(Service.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    



    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Service.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Service.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Service.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Service.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Service().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
